# Generated by Django 4.0.5 on 2022-06-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
